import { PlaceCtaProps } from './component/PlaceCta';

interface DataProps extends PlaceCtaProps {
  key?: number | string;
}
interface SectionProps {
  heading: string;
  description?: string;
  data: DataProps[] | [DataProps[]];
  orientation?: 'horizontal' | 'vertical';
}

interface HomeMockDataProps {
  sections: { [key: string]: SectionProps };
}

const HOME_MOCK_DATA: HomeMockDataProps = {
  sections: {
    placeCtas: {
      heading: 'Find your getaway',
      description:
        'Our spaces are designed for comfort - whether you are working, relaxing, or craving some spaces',
      data: [
        {
          key: 1,
          place: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
          image: {
            uri: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80',
          },
          imageLabel: 'From $126',
        },
        {
          key: 2,
          place: '409 St. Jacques | 2 Br',
          location: 'Old Montreal, Montreal',
          image: {
            uri: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80',
          },
          imageLabel: 'From $126',
        },
        {
          key: 3,
          place: '409 St. Jacques | 2 Br',
          location: 'Old Montreal, Montreal',
          image: {
            uri: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80',
          },
          imageLabel: 'From $126',
        },
        {
          key: 4,
          place: '409 St. Jacques | 2 Br',
          location: 'Old Montreal, Montreal',
          image: {
            uri: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80',
          },
          imageLabel: 'From $126',
        },
      ],
    },
    cityCtas: {
      heading: '20+ cities to explore',
      orientation: 'horizontal',
      data: [
        [
          {
            key: 1,
            image: {
              uri: 'https://images.unsplash.com/photo-1597535973747-951442d5dbc7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
            },
            place: 'Miami',
          },
          {
            key: 2,
            image: {
              uri: 'https://images.unsplash.com/photo-1500916434205-0c77489c6cf7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
            },
            place: 'New York',
            imageLabel: 'New',
          },
          {
            key: 3,
            image: {
              uri: 'https://images.unsplash.com/photo-1547401061-7fbd33ec9021?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
            },
            place: 'Montreal',
          },
          {
            key: 4,
            image: {
              uri: 'https://images.unsplash.com/photo-1554321585-ef3194b190cd?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
            },
            place: 'Vancouver',
          },
          {
            key: 5,
            image: {
              uri: 'https://images.unsplash.com/photo-1586576782138-19304c43d0e1?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
            },
            place: 'Toronto',
          },
        ],
      ],
    },
  },
};

export type { HomeMockDataProps, SectionProps, DataProps };
export default HOME_MOCK_DATA;

// const placeholderImage =
//   'https://images.unsplash.com/photo-1445116572660-236099ec97a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80';

// const homeMockData = {
//   sections: {
//     placeCtas: {
//       title: 'Find your getaway',
//       description:
//         'Our spaces are designed for comfort - whether you are working, relaxing, or craving some spaces',
//       places: [
//         {
//           id: 2,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 9,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 16,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 23,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 30,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 37,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 44,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 51,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 58,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 65,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 72,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 79,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 86,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 93,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 100,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 107,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 114,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 121,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 128,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 135,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 142,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 149,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 156,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 163,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 170,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 177,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 184,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 191,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 198,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 205,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 212,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 219,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 226,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 233,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 240,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 247,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 254,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 261,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 268,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 275,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 282,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 289,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 296,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 303,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 310,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 317,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 324,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 331,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 338,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 345,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 352,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 359,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 366,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 373,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 380,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 387,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 394,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 401,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 408,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 415,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 422,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 429,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 436,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 443,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 450,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 457,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 464,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 471,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 478,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 485,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 492,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 499,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 506,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 513,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 520,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 527,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 534,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 541,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 548,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 555,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 562,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 569,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 576,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 583,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 590,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 597,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 604,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 611,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 618,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 625,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 632,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 639,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 646,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 653,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 660,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 667,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 674,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 681,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 688,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 695,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 702,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 709,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 716,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 723,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 730,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 737,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 744,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 751,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 758,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 765,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 772,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 779,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 786,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 793,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 800,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 807,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 814,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 821,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 828,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 835,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 842,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 849,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 856,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 863,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 870,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 877,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 884,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 891,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 898,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 905,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 912,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 919,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 926,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 933,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 940,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 947,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 954,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 961,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 968,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 975,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 982,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 989,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 996,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1003,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1010,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1017,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1024,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1031,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1038,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1045,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1052,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1059,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1066,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1073,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1080,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1087,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1094,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1101,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1108,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1115,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1122,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1129,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1136,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1143,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1150,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1157,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1164,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1171,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1178,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1185,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1192,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1199,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1206,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1213,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1220,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1227,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1234,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1241,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1248,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1255,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1262,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1269,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1276,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1283,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1290,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1297,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1304,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1311,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1318,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1325,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1332,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1339,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1346,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1353,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1360,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1367,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1374,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1381,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1388,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1395,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1402,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1409,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1416,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1423,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1430,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1437,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1444,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1451,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1458,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1465,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1472,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1479,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1486,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1493,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1500,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1507,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1514,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1521,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1528,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1535,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1542,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1549,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1556,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1563,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1570,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1577,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1584,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1591,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1598,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1605,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1612,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1619,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1626,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1633,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1640,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1647,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1654,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1661,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1668,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1675,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1682,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1689,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1696,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1703,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1710,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1717,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1724,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1731,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1738,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1745,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1752,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1759,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1766,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1773,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1780,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1787,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1794,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1801,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1808,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1815,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//         {
//           id: 1822,
//           image: placeholderImage,
//           imageLabel: 'From $126',
//           title: '408 St. Jacques | 1 Br',
//           location: 'Old Montreal, Montreal',
//         },
//       ],
//     },
//     cityCtas: {
//       title: '20+ cities to explore',
//       places: [
//         {
//           key: 1,
//           image: {
//             uri: 'https://images.unsplash.com/photo-1597535973747-951442d5dbc7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
//           },
//           place: 'Miami',
//         },
//         {
//           key: 2,
//           image: {
//             uri: 'https://images.unsplash.com/photo-1500916434205-0c77489c6cf7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
//           },
//           place: 'New York',
//           imageLabel: 'New',
//         },
//         {
//           key: 3,
//           image: {
//             uri: 'https://images.unsplash.com/photo-1547401061-7fbd33ec9021?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
//           },
//           place: 'Montreal',
//         },
//         {
//           key: 4,
//           image: {
//             uri: 'https://images.unsplash.com/photo-1554321585-ef3194b190cd?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
//           },
//           place: 'Vancouver',
//         },
//         {
//           key: 5,
//           image: {
//             uri: 'https://images.unsplash.com/photo-1586576782138-19304c43d0e1?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300',
//           },
//           place: 'Toronto',
//         },
//       ],
//     },
//   },
// };
